title: "Mert's Blog"
author: "Mert Bozkir"
description: "A blog about my life, Data Science and MLOps"
permalink: /:year/:month/:title/
lang: "en"
excerpt_separator: "\n\n\n\n"
date_format: "%B %d, %Y"


# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
show_title: true          # always keep the site title visible

# Styling

dark_header: true      # always keep the header dark
minimal: false         # use simpler style

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", icon: home}
  - {file: "projects.md", icon: clipboard}
  - {file: "README.md", icon: address-card}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
#   - {title: Mail, icon: envelope, url: "mailto:mert.bozkirr@gmail.com"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/in/mertbozkir", target: '_blank'} 
  - {title: Github, icon: github, url: "https://github.com/mertbozkir", target: '_blank'}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/mertbozkirr", target: '_blank'}
#   - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
# disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed



