baseurl = "https://mertbozkir.com"
metaDataFormat = "yaml"
title = "Mert's Bert"
theme = "blist"

commentable = true

[languages]
  [languages.en]
    contentDir = "content" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Mert Bozkir"
      introSubtitle = "Self-learner on Machine Learning who enjoys latin dances, extreme sports and self-awareness"
      introPhoto = "/photo.jpg"
      logo = "/blue.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "about"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "Top Post"
        url = "/blog/emoji-support/"
        weight = 4

 
[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Mert Bozkir · All rights reserved"
  favicon = "/favicon/favicon.ico"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-400"
  author = "Mert Bozkir"
  # The page bundle that is shown on the front page
  frontBundle = "blog"
  
[params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
  enable = true
  repo = "mertbozkir/mertbozkir.github.io"    # The repo to store comments
  issueTerm = "pathname"
  theme="preferred-color-scheme"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "I am documenting my Data Science and MLOps Journey!"
  linkedin = "https://linkedin.com/in/mertbozkir"
  twitter = "https://twitter.com/mertbozkirr"
  github = "https://github.com/mertbozkir" 
  medium = "https://medium.com/@mertbozkir"
  # reddit = "https://reddit.com/"
  # dribbble = "https://dribbble.com/"
  # youtube = ""
  # email = "mertbozkirr@gmail.com"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true



